from rocketchat_API.rocketchat import RocketChat

rocket = RocketChat('akiel', 'qweqwe123!')
# pprint(rocket.me().json())
# pprint(rocket.info().json())
# pprint(rocket.users_info('AFmxxCpmAj5pgSoBy').json())
# pprint(rocket.chat_post_message('GENERAL', 'hola por aqui', alias='jorge').json())
# pprint(rocket.chat_delete('GENERAL', 'KnjiERFALoE5rh4oD').json())
# pprint(rocket.chat_update('GENERAL', 'kkhiGNohm27yqJFXZ', ':D').json())
# pprint(rocket.channels_info('GENERAL').json())
# pprint(rocket.channels_history('GENERAL', count=1).json())
# pprint(rocket.channels_list().json())
# pprint(rocket.im_list().json())
# pprint(rocket.im_history(room_id='AFmxxCpmAj5pgSoByRsiuHzzh24MKTTQkw', oldest='2017-03-12T05:28:33.662Z').json())
# pprint(rocket.chat_post_message('AFmxxCpmAj5pgSoByRsiuHzzh24MKTTQkw', ';)').json())
# pprint(rocket.groups_list().json())
# pprint(rocket.groups_history('7rqeNcGj6QRbnMFfM', oldest='2017-03-12T05:48:37.530Z').json())
#
# pprint(rocket.users_list().json())
# pprint(rocket.users_get_presence('RsiuHzzh24MKTTQkw').json())
# pprint(rocket.channels_list_joined().json())
# pprint(rocket.logout().json())
# pprint(rocket.im_close(room_id='QYEXwK9t39fMZN8pcwqXAy44Pxo2GCwFCM').json())
# pprint(rocket.im_open(room_id='QYEXwK9t39fMZN8pcwqXAy44Pxo2GCwFCM').json())
# pprint(rocket.im_list().json())
# pprint(rocket.im_messages_others(room_id='QYEXwK9t39fMZN8pcwqXAy44Pxo2GCwFCM').json())
# pprint(rocket.im_list_everyone().json())
# pprint(rocket.im_set_topic(room_id='QYEXwK9t39fMZN8pcwqXAy44Pxo2GCwFCM', topic='testing my demo'))
# pprint(rocket.channels_add_all('gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_add_moderator(room_id='gBZcA87wc9JJPHcio', user_id='wqXAy44Pxo2GCwFCM').json())
# pprint(rocket.channels_add_owner(room_id='gBZcA87wc9JJPHcio', user_id='wqXAy44Pxo2GCwFCM').json())
# pprint(rocket.channels_archive(room_id='gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_unarchive(room_id='gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_history(room_id='gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_clean_history(room_id='gBZcA87wc9JJPHcio', latest='2017-03-20T23:23:32.039Z',
#                                      oldest='2017-03-20T23:33:17.607Z').json())
# pprint(rocket.channels_history(room_id='gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_close(room_id='gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_open(room_id='gBZcA87wc9JJPHcio').json())
# pprint(rocket.channels_create(name='otro2').json())
# pprint(rocket.channels_get_integrations(room_id='GENERAL').json())
# pprint(rocket.channels_list().json())
# pprint(rocket.channels_invite(room_id='FjTprLQjSd9aQku3F', user_id='wqXAy44Pxo2GCwFCM').json())
# pprint(rocket.channels_kick(room_id='FjTprLQjSd9aQku3F', user_id='wqXAy44Pxo2GCwFCM').json())
# pprint(rocket.channels_leave(room_id='FjTprLQjSd9aQku3F').json())
# pprint(rocket.channels_remove_moderator(room_id='gBZcA87wc9JJPHcio', user_id='wqXAy44Pxo2GCwFCM').json())
# pprint(rocket.channels_remove_owner(room_id='gBZcA87wc9JJPHcio', user_id='wqXAy44Pxo2GCwFCM').json())
# pprint(rocket.channels_rename(room_id='gBZcA87wc9JJPHcio', name='canal_zero').json())
# pprint(rocket.channels_set_description(room_id='gBZcA87wc9JJPHcio', description='canal_zero así').json())
# pprint(rocket.channels_set_join_code(room_id='gBZcA87wc9JJPHcio', join_code='qweqwe123').json())
# pprint(rocket.channels_set_read_only(room_id='gBZcA87wc9JJPHcio', read_only=True).json())
# pprint(rocket.channels_set_topic(room_id='gBZcA87wc9JJPHcio', topic='hola mundo').json())
# pprint(rocket.channels_set_type(room_id='gBZcA87wc9JJPHcio', a_type='p').json())
# print(rocket.settings_get(_id='Livechat_enabled').json())
# print(rocket.settings_update(_id='Livechat_enabled', value=True).json())
# print(rocket.settings_get(_id='Livechat_enabled').json())
